compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  game-input:
    npmAuthToken: "${NPM_AUTH_TOKEN:-}"
    npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
