name: Execute commmand for each package
description: Execute commmand for each package. The command is first executed for the "core" package and for the adapters afterwards.

inputs:
    command:
        required: true
        type: string

runs:
    using: composite
    steps:
        - shell: bash
          run: ${GITHUB_ACTION_PATH}/action.sh "${{ inputs.command }}"
